# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 030334323ab0a17702f510a0650cd1668735cc992af256ef078a18a89a68789b4fc84185bee4de37d15422149f6ab2f2abcf5a1863855c813bcd61e160a6248a

test:
  secret_key_base: 762faf847462d9736e38a1ede7b2c46dd533e08efcf0d7f41f073d7afcbff9925dfd381764ab4922c7cf36fa81d5fbb44d452d6ce5fc1688a0cde584c715d73b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
